package models

import (
	"database/sql"
	"time"
)

// Micro lesson job statuses
const (
	MicroJobStatusQueued     = "queued"
	MicroJobStatusProcessing = "processing"
	MicroJobStatusCompleted  = "completed"
	MicroJobStatusFailed     = "failed"
)

// Micro lesson statuses
const (
	MicroLessonStatusDraft     = "draft"
	MicroLessonStatusPublished = "published"
	MicroLessonStatusArchived  = "archived"
)

// MicroLessonJob represents a generation job — one job produces many lessons.
type MicroLessonJob struct {
	ID              int64          `json:"id" db:"id"`
	CourseID        int64          `json:"course_id" db:"course_id"`
	SectionID       sql.NullInt64  `json:"section_id" db:"section_id"`
	SourceContentID sql.NullInt64  `json:"source_content_id" db:"source_content_id"`
	SourceFilePath  sql.NullString `json:"source_file_path" db:"source_file_path"`
	SourceFileType  sql.NullString `json:"source_file_type" db:"source_file_type"`
	SourceURL       sql.NullString `json:"source_url" db:"source_url"`
	TargetMinutes   int            `json:"target_minutes" db:"target_minutes"`
	Language        string         `json:"language" db:"language"`
	Status          string         `json:"status" db:"status"`
	Progress        int            `json:"progress" db:"progress"`
	Stage           string         `json:"stage" db:"stage"`
	LessonsCount    int            `json:"lessons_count" db:"lessons_count"`
	Error           sql.NullString `json:"error" db:"error"`
	CreatedBy       int64          `json:"created_by" db:"created_by"`
	CreatedAt       time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at" db:"updated_at"`
	CompletedAt     sql.NullTime   `json:"completed_at" db:"completed_at"`
}

// MicroLesson represents a single bite-sized lesson (~5 min) generated by AI.
type MicroLesson struct {
	ID                  int64          `json:"id" db:"id"`
	JobID               int64          `json:"job_id" db:"job_id"`
	CourseID            int64          `json:"course_id" db:"course_id"`
	SectionID           sql.NullInt64  `json:"section_id" db:"section_id"`
	SourceContentID     sql.NullInt64  `json:"source_content_id" db:"source_content_id"`
	Title               string         `json:"title" db:"title"`
	Summary             sql.NullString `json:"summary" db:"summary"`
	Objectives          []byte         `json:"objectives" db:"objectives"`
	MarkdownContent     string         `json:"markdown_content" db:"markdown_content"`
	EstimatedMinutes    int            `json:"estimated_minutes" db:"estimated_minutes"`
	OrderIndex          int            `json:"order_index" db:"order_index"`
	Status              string         `json:"status" db:"status"`
	PublishedContentID  sql.NullInt64  `json:"published_content_id" db:"published_content_id"`
	NodeID              sql.NullInt64  `json:"node_id" db:"node_id"`
	ImageURLs           []byte         `json:"image_urls" db:"image_urls"`
	Language            string         `json:"language" db:"language"`
	CreatedBy           int64          `json:"created_by" db:"created_by"`
	CreatedAt           time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at" db:"updated_at"`
	PublishedAt         sql.NullTime   `json:"published_at" db:"published_at"`
}